version: "3.5"

services:
  broker1:
    container_name: broker1
    image: netifi/broker:${DOCKER_BROKER_IMAGE_VERSION}
    environment:
      - "BROKER_SERVER_OPTS=-Dnetifi.broker.ssl.disabled=${NETIFI_BROKER_SSL_DISABLED} -Dnetifi.broker.cluster.clusterName=${NETIFI_BROKER_CLUSTER_CLUSTERNAME} -Dnetifi.authentication.0.accessKey=${NETIFI_AUTHENTICATION_0_ACCESSKEY} -Dnetifi.authentication.0.accessToken=${NETIFI_AUTHENTICATION_0_ACCESSTOKEN} -Dnetifi.broker.admin.accessKey=${NETIFI_BROKER_ADMIN_ACCESSKEY} -Dnetifi.broker.admin.accessToken=${NETIFI_BROKER_ADMIN_ACCESSTOKEN} -Dnetifi.broker.admin.address=0.0.0.0 -Dnetifi.broker.admin.publicAddress=127.0.0.1 -Dnetifi.broker.admin.port=6001 -Dnetifi.broker.cluster.address=0.0.0.0 -Dnetifi.broker.cluster.publicAddress=127.0.0.1 -Dnetifi.broker.cluster.port=7001 -Dnetifi.broker.tcp.address=0.0.0.0 -Dnetifi.broker.tcp.publicAddress=127.0.0.1 -Dnetifi.broker.tcp.port=8001 -Dnetifi.broker.websocket.address=0.0.0.0 -Dnetifi.broker.websocket.publicAddress=127.0.0.1 -Dnetifi.broker.websocket.port=8101"
    ports:
      - "6001:6001"
      - "7001:7001"
      - "8001:8001"
      - "8101:8101"

  broker2:
    container_name: broker2
    image: netifi/broker:${DOCKER_BROKER_IMAGE_VERSION}
    environment:
      - "BROKER_SERVER_OPTS=-Dnetifi.broker.ssl.disabled=${NETIFI_BROKER_SSL_DISABLED} -Dnetifi.broker.cluster.clusterName=${NETIFI_BROKER_CLUSTER_CLUSTERNAME} -Dnetifi.authentication.0.accessKey=${NETIFI_AUTHENTICATION_0_ACCESSKEY} -Dnetifi.authentication.0.accessToken=${NETIFI_AUTHENTICATION_0_ACCESSTOKEN} -Dnetifi.broker.admin.accessKey=${NETIFI_BROKER_ADMIN_ACCESSKEY} -Dnetifi.broker.admin.accessToken=${NETIFI_BROKER_ADMIN_ACCESSTOKEN} -Dnetifi.broker.admin.address=0.0.0.0 -Dnetifi.broker.admin.publicAddress=127.0.0.1 -Dnetifi.broker.admin.port=6002 -Dnetifi.broker.cluster.address=0.0.0.0 -Dnetifi.broker.cluster.publicAddress=127.0.0.1 -Dnetifi.broker.cluster.port=7002 -Dnetifi.broker.tcp.address=0.0.0.0 -Dnetifi.broker.tcp.publicAddress=127.0.0.1 -Dnetifi.broker.tcp.port=8002 -Dnetifi.broker.websocket.address=0.0.0.0 -Dnetifi.broker.websocket.publicAddress=127.0.0.1 -Dnetifi.broker.websocket.port=8102 -Dnetifi.broker.seed.address=127.0.0.1:7001"
    ports:
      - "6002:6002"
      - "7002:7002"
      - "8002:8002"
      - "8102:8102"
    depends_on:
      - broker1

  broker3:
    container_name: broker3
    image: netifi/broker:${DOCKER_BROKER_IMAGE_VERSION}
    environment:
      - "BROKER_SERVER_OPTS=-Dnetifi.broker.ssl.disabled=${NETIFI_BROKER_SSL_DISABLED} -Dnetifi.broker.cluster.clusterName=${NETIFI_BROKER_CLUSTER_CLUSTERNAME} -Dnetifi.authentication.0.accessKey=${NETIFI_AUTHENTICATION_0_ACCESSKEY} -Dnetifi.authentication.0.accessToken=${NETIFI_AUTHENTICATION_0_ACCESSTOKEN} -Dnetifi.broker.admin.accessKey=${NETIFI_BROKER_ADMIN_ACCESSKEY} -Dnetifi.broker.admin.accessToken=${NETIFI_BROKER_ADMIN_ACCESSTOKEN} -Dnetifi.broker.admin.address=0.0.0.0 -Dnetifi.broker.admin.publicAddress=127.0.0.1 -Dnetifi.broker.admin.port=6003 -Dnetifi.broker.cluster.address=0.0.0.0 -Dnetifi.broker.cluster.publicAddress=127.0.0.1 -Dnetifi.broker.cluster.port=7003 -Dnetifi.broker.tcp.address=0.0.0.0 -Dnetifi.broker.tcp.publicAddress=127.0.0.1 -Dnetifi.broker.tcp.port=8003 -Dnetifi.broker.websocket.address=0.0.0.0 -Dnetifi.broker.websocket.publicAddress=127.0.0.1 -Dnetifi.broker.websocket.port=8103 -Dnetifi.broker.seed.address=127.0.0.1:7001"
    ports:
      - "6003:6003"
      - "7003:7003"
      - "8003:8003"
      - "8103:8103"
    depends_on:
      - broker1
